import './bootstrap';
import { createApp } from 'vue/dist/vue.esm-bundler';
import Pestana from './components/Pestana.vue';
import Header from './components/Header.vue';
import HeaderRegistrado from './components/Header-registrado.vue';
import CajasContacto from './components/CajasContacto.vue';
import InfoAdicional from './components/InfoAdicional.vue';
import Input from './components/Input.vue';
import BotonDegraciado from './components/BotonDegraciado.vue';
import CardsComponent from './components/CardsComponent.vue';
import StatsCard from './components/StatsCard.vue';
import Clientes from './components/Clientes.vue';
import Usuarios from './components/Usuarios.vue';
import AccionesRapidasOperador from './components/operador/AccionesRapidasOperador.vue';
import NotificacionesOperador from './components/operador/NotificacionesOperador.vue';
import OfertasRecientesOperador from './components/operador/OfertasRecientesOperador.vue';
import OperacionesRecientesOperador from './components/operador/OperacionesRecientesOperador.vue';
import ResumenOperador from './components/operador/ResumenOperador.vue';
import TablaOfertas from './components/ofertas/TablaOfertas.vue';
import RegisterPage from './paginas/Register.vue';
import Contacto from './paginas/Contacto.vue';
import CrearOfertaPage from './paginas/CrearOferta.vue';
import AnadirCliente from './paginas/AñadirCliente.vue';
import EditarCliente from './paginas/EditarCliente.vue';
import DashboardOperadorCliente from './paginas/DashboardOperadorCliente.vue';
import DetalleOfertaPage from './paginas/DetalleOferta.vue';
import OfertasPage from './paginas/Ofertas.vue';
import OperacionesPage from './paginas/Operaciones.vue';
import QuienesSomos from './paginas/QuienesSomos.vue';
import Valores from './components/Valores.vue';
import DashboardAdministrador from './paginas/DashboardAdministrador.vue';

const app = createApp({});

app.component('pestana-component', Pestana);
app.component('header-component', Header);
app.component('header-registrado', HeaderRegistrado);
app.component('cajas-contacto', CajasContacto);
app.component('info-adicional', InfoAdicional);
app.component('input-component', Input);
app.component('boton-degradado', BotonDegraciado);
app.component('stats-card', StatsCard);
app.component('clientes-tabla', Clientes);
app.component('usuarios-tabla', Usuarios);
app.component('acciones-rapidas-operador', AccionesRapidasOperador);
app.component('notificaciones-operador', NotificacionesOperador);
app.component('ofertas-recientes-operador', OfertasRecientesOperador);
app.component('operaciones-recientes-operador', OperacionesRecientesOperador);
app.component('resumen-operador', ResumenOperador);
app.component('tabla-ofertas', TablaOfertas);
app.component('register-page', RegisterPage);
app.component('contacto-page', Contacto);
app.component('crear-oferta-page', CrearOfertaPage);
app.component('anadir-cliente-page', AnadirCliente);
app.component('editar-cliente', EditarCliente);
app.component('dashboard-operador-cliente-page', DashboardOperadorCliente);
app.component('detalle-oferta-page', DetalleOfertaPage);
app.component('ofertas-page', OfertasPage);
app.component('operaciones-page', OperacionesPage);
app.component('quienes-somos', QuienesSomos);
app.component('cards-component', CardsComponent);
app.component('valores-component', Valores);
app.component('DashboardAdmin', DashboardAdministrador);
app.mount('#app');
