import './bootstrap';
import { createApp } from 'vue/dist/vue.esm-bundler';
import Pestana from './components/Pestana.vue';
import Header from './components/Header.vue';
import HeaderRegistrado from './components/Header-registrado.vue';
import CajasContacto from './components/CajasContacto.vue';
import InfoAdicional from './components/InfoAdicional.vue';
import Input from './components/Input.vue';
import BotonDegraciado from './components/BotonDegraciado.vue';
import CardsComponent from './components/CardsComponent.vue';
import StatsCard from './components/StatsCard.vue';
import Clientes from './components/Clientes.vue';
import RegisterPage from './paginas/Register.vue';
import Contacto from './paginas/Contacto.vue';
import AnadirCliente from './paginas/AñadirCliente.vue';
import EditarCliente from './paginas/EditarCliente.vue';
import QuienesSomos from './paginas/QuienesSomos.vue';
import Valores from './components/Valores.vue';
import DashboardAdministrador from './paginas/DashboardAdministrador.vue';

const app = createApp({});

app.component('pestana-component', Pestana);
app.component('header-component', Header);
app.component('header-registrado', HeaderRegistrado);
app.component('cajas-contacto', CajasContacto);
app.component('info-adicional', InfoAdicional);
app.component('input-component', Input);
app.component('boton-degradado', BotonDegraciado);
app.component('stats-card', StatsCard);
app.component('clientes-tabla', Clientes);
app.component('register-page', RegisterPage);
app.component('contacto-page', Contacto);
app.component('anadir-cliente-page', AnadirCliente);
app.component('quienes-somos', QuienesSomos);
app.component('cards-component', CardsComponent);
app.component("valores-component",Valores);
app.component("DashboardAdmin", DashboardAdministrador)
app.component('editar-cliente', EditarCliente);
app.mount('#app');
