server {
    listen 80;
    server_name localhost;

    root /var/www/public;
    index index.php;

    # Si piden un archivo real, Nginx lo sirve directamente.
    # Si piden una ruta de Laravel, la manda a index.php.
    location / {
        try_files $uri $uri/ /index.php?$query_string;
    }

    # Si hay que ejecutar PHP, Nginx lo manda al servicio app:9000.
    location ~ \.php$ {
        include fastcgi_params;
        fastcgi_pass app:9000;
        fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
    }

    # Si piden archivos ocultos, Nginx los bloquea.
    location ~ /\. {
        deny all;
    }
}
